name: Update Calendar

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'  # runs every day at 5:00 UTC
  workflow_dispatch:      # allow manual run from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SECRET_URL: ${{ secrets.MY_SECRET_URL }}
    permissions:
      # This permission is required for the action to push changes back to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t usycal .

      - name: Docker run once
        run: docker run --env SECRET_URL --name usycal-container usycal

      - name: Copy calendar file from container
        run: docker cp usycal-container:/app/calendar.ics .

      - name: Commit and push calendar.ics
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git diff
          git add calendar.ics
          git commit -m "- update calendar.ics [auto]" || echo "No changes to commit"
          git push
